export const GET_ALL_GROUPS = 'GET_ALL_GROUPS'
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS'
export const GET_ALL_GROUPS_FAILURE = 'GET_ALL_GROUPS_FAILURE'

export const GET_GROUP_BY_ID = 'GET_GROUP_BY_ID'
export const GET_GROUP_BY_ID_SUCCESS = 'GET_GROUP_BY_ID_SUCCESS'
export const GET_GROUP_BY_ID_FAILURE = 'GET_GROUP_BY_ID_FAILURE'

export const POST_CREATE_GROUP = 'POST_CREATE_GROUP'
export const POST_CREATE_GROUP_SUCCESS = 'POST_CREATE_GROUP_SUCCESS'
export const POST_CREATE_GROUP_FAILURE = 'POST_CREATE_GROUP_FAILURE'

export const UPDATE_GROUP = 'UPDATE_GROUP'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE'

export const DELETE_GROUP = 'DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE'
