version: '3'
services:
  proxy:
    image: caddy:2.4.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - global
    depends_on:
      - backend
      - frontend
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    networks:
      - global

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - global

networks:
  global:
    external: true

volumes:
  caddy_data: null
  caddy_config: null
