export const GET_ALL_SLACK_CHANNELS = 'GET_ALL_SLACK_CHANNELS'
export const GET_ALL_SLACK_CHANNELS_SUCCESS = 'GET_ALL_SLACK_CHANNELS_SUCCESS'
export const GET_ALL_SLACK_CHANNELS_FAILURE = 'GET_ALL_SLACK_CHANNELS_FAILURE'

export const GET_SLACK_CHANNELS_DB = 'GET_SLACK_CHANNELS_DB'
export const GET_SLACK_CHANNELS_DB_SUCCESS = 'GET_SLACK_CHANNELS_DB_SUCCESS'
export const GET_SLACK_CHANNELS_DB_FAILURE = 'GET_SLACK_CHANNELS_DB_FAILURE'

export const UPDATE_SLACK_CHANNELS = 'UPDATE_SLACK_CHANNELS'
export const UPDATE_SLACK_CHANNELS_SUCCESS = 'UPDATE_SLACK_CHANNELS_SUCCESS'
export const UPDATE_SLACK_CHANNELS_FAILURE = 'UPDATE_SLACK_CHANNELS_FAILURE'
