export const GET_ALL_SLACK_CHANNELS = 'GET_ALL_SLACK_CHANNELS'
export const GET_ALL_SLACK_CHANNELS_SUCCESS = 'GET_ALL_SLACK_CHANNELS_SUCCESS'
export const GET_ALL_SLACK_CHANNELS_FAILURE = 'GET_ALL_SLACK_CHANNELS_FAILURE'
