export const GET_LIST_POST = 'GET_LIST_POST'
export const GET_LIST_POST_SUCCESS = 'GET_LIST_POST_SUCCESS'
export const GET_LIST_POST_FAILURE = 'GET_LIST_POST_FAILURE'

export const POST_LIST_POST = 'POST_LIST_POST'
export const POST_LIST_POST_SUCCESS = 'POST_LIST_POST_SUCCESS'
export const POST_LIST_POST_FAILURE = 'POST_LIST_POST_FAILURE'
